# Uncomment the next line to define a global platform for your project
platform :iOS, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'AnyRtmp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnyRtmp

end
