# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MQTTDemo2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MQTTDemo2
  pod 'MQTTClient/Websocket'

  target 'MQTTDemo2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MQTTDemo2UITests' do
    # Pods for testing
  end

end
